### ISSUE TITLE
ERROR READ LINE: -32

### ISSUE THREAD

**Issue by vagrant313** [srsran/zynq_timestamping#54]
I am facing an error after running default run_txrx_test_plutosdr.sh as shown below.

![image](https://user-images.githubusercontent.com/30632389/224504011-bf79224a-51d5-40c5-8060-59fea2828ec8.png)

the left side is the output of plutosdr dmesg.

do I need to update srs with metadata libiio driver inside pluto, I have not seen any info about it, Thanks

**Comment by vagrant313** [comment]
i updated the host side libraries as well, but still the same error
![image](https://user-images.githubusercontent.com/30632389/224537412-08d613dd-58f0-48f9-9362-ed4d374ece9b.png)
on the plutosdr
![image](https://user-images.githubusercontent.com/30632389/224537508-0712ecb5-156f-42ae-82cd-58a33c003721.png)

**Comment by vagrant313** [comment]
1. I am directly running the system_top.bit.bin provided in the release. 
2. runnig the below commands
 
![image](https://user-images.githubusercontent.com/30632389/224555260-4a3699e3-6664-425e-91cb-0862d6551254.png)

3. ./run_txrx_pluo.sh

![image](https://user-images.githubusercontent.com/30632389/224555435-76ad531c-be73-415e-98d4-0fbbd7a7e760.png)

seems like its the issue of uboot memory space is not matching with the current bootfiles used in the default plutosdr image.
do i need to build bootfiles from scratch?
It should run as defined in the documentation.

**Comment by vagrant313** [comment]
Hi, 
The porblem is solved and just adding here ifanyone finds the same issu, it was the issue of libiio and srs comatibility versions.

first update the pluto firmware version

https://wiki.analog.com/university/tools/pluto/users/firmware

a. check the current verion iio_info -s should be v0.23 b.

https://github.com/analogdevicesinc/plutosdr-fw/releases/tag/v0.34

copy all te files of plutosdr-fw-v0.34.zip to plutoSDR drive

Eject usb

wait for blibking led about 4minuts

reboot pluto

install libiio ver 0.23 which is compatible with srs 2019.1 bitfile

https://github.com/analogdevicesinc/plutosdr-fw/releases/tag/v0.34

install libiio-ad936x

wget http://swdownloads.analog.com/cse/travis_builds/master_latest_libad9361-iio-ubuntu-18.04-amd64.deb

**Comment by ofontbach** [comment]
Thanks for your inputs @vagrant313!
