### ISSUE TITLE
The correct output of test app run_txrx_plutosdr.sh

### ISSUE THREAD

**Issue by vagrant313** [srsran/zynq_timestamping#55]
Hi,
I am testing the given app on the zynq7020 platform, and getting below logs and output plot. can anyone confirm my results are correct. It was stated in the documentation, the app will transmit the tomes at distinct 4msec. Please confirm.. Thanks

![image](https://user-images.githubusercontent.com/30632389/229354031-04ea393f-1ab0-4e6c-bac6-4efc48c1476c.png)

Opening RF device...
Active RF plugins: libsrsran_rf_iio.so
Inactive RF plugins:
Supported RF device list: iio
Trying to open RF device 'iio'
CH0 n_prb=6
CH0 context=ip:10.42.0.133
RF device 'iio' successfully opened
Subframe len:   1920 samples
Time advance:   0.000000 us
Set TX/RX rate: 1.92 MHz
Set RX gain:    15.0 dB
Set TX gain:    40.0 dB
Set TX/RX freq: 2400.00 MHz
Set TONE : TransmittionRx subframe 0
Transmitting Signal
Rx subframe 1
Rx subframe 2
Rx subframe 3
Transmitting Signal
Rx subframe 4
Rx subframe 5
Rx subframe 6
Rx subframe 7
Rx subframe 8
Transmitting Signal
Rx subframe 9
Rx subframe 10
Rx subframe 11
Rx subframe 12
Rx subframe 13
Rx subframe 14
Rx subframe 15
Rx subframe 16
Rx subframe 17
Rx subframe 18
Rx subframe 19
Done

**Comment by ofontbach** [comment]
Hi @vagrant313,

The plot you are showing is indeed as expected. Note that the first transmission happens with 4 ms of latency (that's around 1920*4 samples) and the following ones take place as expected with a separation of 3 ms and 8 ms with respect to the first one - see this  [line of code in txrx_test.c](https://github.com/srsran/zynq_timestamping/blob/38ba060b5a64387488534ae1bfc4b78d35342dbe/app/txrx_test.c#L180).

Regards,
