### ISSUE TITLE
ADALM-PLUTO Project Build Stuck in Ubuntu 20.04

### ISSUE THREAD

**Issue by chaohwa4** [srsran/zynq_timestamping#56]
I tried to build the ADALM-PLUTO project with Ubuntu 20.04. I used python3.10 to build the python tools. However, when I typed "/create_project.sh bitstream", the project was stuck with axi_ad9361 and I used Ctrl-C to exit the building process.

haohwa@chaohwa-ThinkPad-Edge-E540:~/zynq_timestamping/projects/pluto$ ./create_project.sh bitstream
###################################################################
- Mode: bitstream
###################################################################
Building axi_ad9361 library [/home/chaohwa/zynq_timestamping/projects/pluto/hdl/library/axi_ad9361/axi_ad9361_ip.log] ...^Cmake[1]: *** [../scripts/library.mk:71: component.xml] Interrupt
make: *** [Makefile:55: gen-adi-ips] Interrupt

In my Ubuntu 20.04, the cmake version is 3.16.3. The gcc version is 9.4.0. 

However, I don't have any problem building the project in Ubuntu 18.04. So how should I fix it in Ubuntu 20,04?

**Comment by ofontbach** [comment]
Hi @chaohwa4,
I've just tried building the ADALM-PLUTO project and it worked perfectly fine for me with the following versions:
- Ubuntu 20.04.3 LTS
- python3 3.8.10
- gcc 9.4.0
- cmake 3.26
- Vivado 2019.2.1
Cheers

**Comment by chaohwa4** [comment]
So far the differences are Ubuntu and cmake. My versions are Ubuntu 20.04.6 and cmake 3.16.3.

**Comment by chaohwa4** [comment]
Even if I upgrade cmake to 3.26.3. It is still stuck in building axi_ad9361 library. So I might as well converting Ubuntu to 20.04.3 and test there. At least Ubuntu 18.04.6 works.

**Comment by chaohwa4** [comment]
How do you keep your OS version as 20.04.3? When I use software update to update the system, it will update to 20.04.6, which I don't want to do because building axi_ad9361 library is getting stuck again!

**Comment by chaohwa4** [comment]
This is how it was stuck:

chaohwa@chaohwa-ThinkPad-Edge-E540:~/zynq_timestamping/projects/pluto$ more hdl/library/axi_ad9361/axi_ad9361_ip.log
application-specific initialization failed: couldn't load file "librdi_commontasks.so": libtinfo.so.5: cannot open shared object file: No such
 file or directory
%

**Comment by chaohwa4** [comment]
After performing the following, the process started working:

cd /lib/x86_64-linux-gnu
sudo ln -s libtinfo.so.6 libtinfo.so.5

**Comment by chaohwa4** [comment]
In short, for Ubuntu 20.04 or 22.04, when stuck in building axi_ad9361 library after executing "./create_project.sh bitstream", do the following:
cd /lib/x86_64-linux-gnu
sudo ln -s libtinfo.so.6 libtinfo.so.5

It will solve the library stuck issue.

**Comment by ofontbach** [comment]
Thanks for the tip @chaohwa4!
