### ISSUE TITLE
python_tools installation fails

### ISSUE THREAD

**Issue by quicktel** [srsran/zynq_timestamping#9]
Hello,

Projects build documentation mentions the following:

```
Prerequisites: 

SRS Python tools:

cd python_tools
sudo pip3 install .

```
However, this command is failing as pip3 is unable to find "setup.py" file.

Please add setup.py to fix this issue.

Regards.

**Comment by qarlosalberto** [comment]
Could you share your log?

**Comment by qarlosalberto** [comment]
Update pip: 

```
sudo pip3 install -U pip
```

**Comment by quicktel** [comment]
Agreed, I just upgraded pip and is working. I was using python < 3.6

**Comment by quicktel** [comment]
Thank you
